$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  transports: [console, file]
  level: info
  show_progress: true
  path_settings:
    path_pattern: "logs/mcp-agent-{unique_id}.jsonl"
    unique_id: "timestamp" # Options: "timestamp" or "session_id"
    timestamp_format: "%Y%m%d_%H%M%S"

mcp:
  servers:
    g-search: 
      command: "npx"
      args: ["-y", "g-search-mcp", "--debug"]

    fetcher:
      command: "npx"
      args: ["-y", "fetcher-mcp", "--debug"]

    sequential-thinking: 
      command: "npx"
      args: [
        "-y",
        "@modelcontextprotocol/server-sequential-thinking"
      ]
      env: 
        MAX_HISTORY_SIZE: "1000"
    
    mcp-registry: 
      command: "npx"
      args: [
        "-y",
        "mcp-server-mcp-registry@latest"
      ]

    mcp-compass: 
      command: "npx"
      args: [
         "-y",
         "@liuyoshio/mcp-compass"
      ]

    filesystem: 
      command: "npx"
      args: [
        "-y",
        "@modelcontextprotocol/server-filesystem",
        "~/Desktop/Vela/vela-temp"
      ]

    context7: 
      command: "npx"
      "args": ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-163b2b07-b9aa-4b35-9892-a8c3b0f9020b"]

google:
  default_model: "gemini-3-pro-preview"
    
openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  #  default_model: "o3-mini"
  default_model: "gpt-5.1" # use better models