[project]
name = "vela-temp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mcp-agent[google,openai]>=0.2.6",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
]
